if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VARIABLE)
    message(FATAL_ERROR "INPUT, OUTPUT, and VARIABLE are required")
endif()

file(READ "${INPUT}" payload HEX)
string(LENGTH "${payload}" payload_length)
math(EXPR byte_count "${payload_length} / 2")

set(contents "#pragma once\n#include <cstddef>\n#include <cstdint>\n")
string(APPEND contents "static constexpr std::uint32_t ${VARIABLE}[] = {\n")
set(column 0)
if(byte_count GREATER 0)
    math(EXPR last_byte "${byte_count} - 1")
    foreach(index RANGE 0 ${last_byte} 4)
        math(EXPR remaining "${byte_count} - ${index}")
        if(remaining GREATER_EQUAL 4)
            math(EXPR character "${index} * 2")
            string(SUBSTRING "${payload}" "${character}" 8 word_hex)
        else()
            set(word_hex "")
            foreach(offset RANGE 0 3)
                if(offset LESS remaining)
                    math(EXPR character "(${index} + ${offset}) * 2")
                    string(SUBSTRING "${payload}" ${character} 2 byte_hex)
                else()
                    set(byte_hex "00")
                endif()
                set(word_hex "${byte_hex}${word_hex}")
            endforeach()
            string(APPEND contents "    0x${word_hex}u,\n")
            continue()
        endif()
        string(SUBSTRING "${word_hex}" 0 2 b0)
        string(SUBSTRING "${word_hex}" 2 2 b1)
        string(SUBSTRING "${word_hex}" 4 2 b2)
        string(SUBSTRING "${word_hex}" 6 2 b3)
        string(APPEND contents "    0x${b3}${b2}${b1}${b0}u,\n")
    endforeach()
endif()
string(APPEND contents "};\n")
string(APPEND contents
    "static constexpr std::size_t ${VARIABLE}_size = ${byte_count};\n")
file(WRITE "${OUTPUT}" "${contents}")
